default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: "password"
  port: 3306
  host: 127.0.0.1

development:
  <<: *default
  database: rails_smartfit_challenge_development

test:
  <<: *default
  database: rails_smartfit_challenge_test

production:
  <<: *default
  database: rails_smartfit_challenge_production
